[workspace]
members = ["exercise/*", "tutorial", "road-race"]
resolver = "2"

[profile.dev]
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
incremental = false
codegen-units = 16
